name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # - name: Clean build environment
          #   run: ./clean.sh
          - name: Regenerate .config from defconfig
            run: |
              rm -f buildroot/.config
              pushd buildroot
              make BR2_DEFCONFIG=../base_external/configs/aesd_qemu_defconfig defconfig
              popd
              grep LIBC buildroot/.config  # Para depuración, podés quitarlo si no hace falta
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
