name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Force clean output and Buildroot toolchain
            run: |

              ./clean.sh

              echo "Cleaning buildroot output directory..."
              rm -rf buildroot/output/build/glibc*
              rm -rf buildroot/output

              echo "Cleaning toolchain host directory..."
              rm -rf buildroot/output/host
              rm -rf buildroot/output/staging

              echo "Cleaning buildroot .config (if exists)..."
              rm -f buildroot/.config

              echo "Setting BR2_DL_DIR to /tmp/.dl to avoid cached toolchain"
              export BR2_DL_DIR=/tmp/.dl
              mkdir -p $BR2_DL_DIR
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
